nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$) 
    documentation:
        info:
            title: API BookMe - Gestion de rendez-vous
            description: Documentation complète de l'API de prise de rendez-vous.
            version: 1.0.0
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - bearerAuth: []
